sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
env:
  global:
    - secure: "r1FmHx69xI7O4KBdJ72eGQvPr3KoO8VebEyTQ7WI0cxCBNQZt2pz05hcljvUXaU8LwALn7T2H+vzB/N34fg3qbEyDPeFWvAnli4eUMTqu4Ham/ppQSKFQNP653UehasCM9xW1Tas5EYV3X1327G2rKlfCJLdePcmxcAmm+dsJOj2MRtzsReT82f6dlwZidKE0EPESZk7Ghh31h7YByIfeLmCCaM3Hkjb2UJm1lN21AwMlUB4d4p0Xhse71n3oOEZeFIvg5WTN4bL9ll5nU/YVx94iQbEX+GEy9rQjhp5nTe5bJ5lKNFNZEVw3pBqnzaZkrJfdk2mOmUw4Y2VJ0c0BfD9/D/UF4xd5AdK02kO0zlODyKK9Ry6pbYlPRmhBQa70u2BwcEqEp6cLH/HBKq313a5kdCDuo1IPfP3ocvxn1sIRs5fS/QutZFT3EowI9S5t8xxw6lZ2ZcTtDDkjM3Kh44jqf4Rm6FBu7hERncxelqzmjIZg5zuCke4F+oWV26i5sXthhCs/HOqADcFU5K6wsatX0MIWu6jZlbK8OMGJNTKxmmw07XArNB7AQLAXmeLiBzU2A8Zv30/uKpCwGxvJjCmM0fmI8xcMdNpJ69mnfCdk2eelRGLCVh5BCHRjHV54m9JPeSEGdsZDqoI/d9zxMWTkeYHgpdzAOOt9Wtdxuo="
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: backendppp
  edge:
    branch: master