language: java
jdk:
 - oraclejdk8
<<<<<<< HEAD
before_install:
=======
 before_install:
>>>>>>> 0c26d9da32fcfd26497506d0d2904d436a3a5392
  - chmod +x mvnw
deploy:
 provider: heroku
 api-key: 
  secure: 828fd708-9607-4fad-909d-0ba9a42f7c85
 app: backendapp
